apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    include.release.openshift.io/single-node-production-edge: "true"
  name: openshift-config-managed
  labels:
    openshift.io/run-level: "0"
