apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: featuregates.config.openshift.io
spec:
  group: config.openshift.io
  version: v1
  scope: Cluster
  names:
    kind: FeatureGate
    singular: featuregate
    plural: featuregates
    listKind: FeatureGateList
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object's metadata.
          type: object
        spec:
          description: spec holds user settable values for configuration
          properties:
            featureSet:
              description: featureSet changes the list of features in the cluster.  The
                default is empty.  Be very careful adjusting this setting. Turning
                on or off features may cause irreversible changes in your cluster
                which cannot be undone.
              type: string
          type: object
        status:
          description: status holds observed values from the cluster. They may not
            be overridden.
          type: object
      required:
      - spec
