apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-operator
  namespace: openshift-config-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: metrics.openshift-config-operator.svc
  jobLabel: component
  namespaceSelector:
    matchNames:
    - openshift-config-operator
  selector:
    matchLabels:
      app: openshift-config-operator

